[elasticsearch]
es01 ansible_host=192.168.1.21 es_node_name=es01
es02 ansible_host=192.168.1.22 es_node_name=es02
es03 ansible_host=192.168.1.23 es_node_name=es03

[elasticsearch:vars]
es_bootstrap_node=es01

[kibana]
kibana ansible_host=192.168.1.24

[fleet_server]
fleet ansible_host=192.168.1.25

[logstash]
logstash ansible_host=192.168.1.26

[elk_stack:children]
elasticsearch
kibana
fleet_server
logstash

# ---- Clients — add your hosts here after the stack is up -----------------
[linux_clients]
# example: web01 ansible_host=192.168.10.50
dns ansible_host=192.168.1.53
workstation ansible_host=192.168.1.163
quanet01 ansible_host=192.168.1.168
openvpn ansible_host=192.168.1.200

[windows_clients]
# example: win01 ansible_host=192.168.10.60 ansible_user=Administrator ansible_connection=winrm ansible_winrm_server_cert_validation=ignore

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
